# Generated by Django 2.1.4 on 2018-12-27 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='公司的项目名称，用于构建分类', max_length=100, unique=True, verbose_name='项目名称')),
            ],
            options={
                'verbose_name': '公司项目',
                'verbose_name_plural': '公司项目',
            },
        ),
        migrations.CreateModel(
            name='JenkinsEnv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='由于有些公司不只一个 Jenkins，该名称用于区分', max_length=100, verbose_name='环境名称')),
                ('url', models.CharField(help_text='Jenkins 的访问地址', max_length=250, verbose_name='URL地址')),
                ('username', models.CharField(help_text='Jenkins 登录用户名', max_length=100, verbose_name='用户名')),
                ('api_token', models.CharField(help_text='基于用户的 Token，在 Jenkins 登录后，点击右上角用户名，再点击左边的设置可以配置 Token', max_length=100, verbose_name='API Token')),
            ],
            options={
                'verbose_name': 'Jenkins 平台',
                'verbose_name_plural': 'Jenkins 平台',
            },
        ),
        migrations.CreateModel(
            name='JenkinsProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='配置任务的名称，用于区分', max_length=100, verbose_name='名称')),
                ('project_name', models.CharField(help_text='配置在 Jenkins 任务的全称', max_length=100, verbose_name='构建任务名称')),
                ('company_project', models.ForeignKey(help_text='配置任务所属的项目', on_delete=django.db.models.deletion.CASCADE, related_name='company_project', to='jenkins_build.CompanyProject', verbose_name='项目')),
                ('jenkins_env', models.ForeignKey(help_text='配置任务所在的 Jenkins', on_delete=django.db.models.deletion.CASCADE, related_name='jenkins_env', to='jenkins_build.JenkinsEnv', verbose_name='环境')),
            ],
            options={
                'verbose_name': '构建任务',
                'verbose_name_plural': '构建任务',
            },
        ),
    ]
